spring:
  config:
    activate:
      on-profile: default
    import: 'aws-parameterstore:'

  datasource:
    url: jdbc:mysql://localhost:3308/order?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 3000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${access.key}
      secret-key: ${secret.key}

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: orderapi

---

spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'

  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    hikari:
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 3000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${access.key}
      secret-key: ${secret.key}

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: orderapi

